//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string class_id { get; set; }
        public string grade_id { get; set; }
        public string subject_id { get; set; }
        public string teacher_id { get; set; }
        public string student_id { get; set; }
    }
}
